<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FotografiaAnuncio', 'doctrine');

/**
 * BaseFotografiaAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idAnuncio
 * @property text $descripcion
 * @property string $fotografia
 * @property boolean $borrado
 * @property boolean $activo
 * @property Anuncio $Anuncio
 * 
 * @method integer           getIdAnuncio()   Returns the current record's "idAnuncio" value
 * @method text              getDescripcion() Returns the current record's "descripcion" value
 * @method string            getFotografia()  Returns the current record's "fotografia" value
 * @method boolean           getBorrado()     Returns the current record's "borrado" value
 * @method boolean           getActivo()      Returns the current record's "activo" value
 * @method Anuncio           getAnuncio()     Returns the current record's "Anuncio" value
 * @method FotografiaAnuncio setIdAnuncio()   Sets the current record's "idAnuncio" value
 * @method FotografiaAnuncio setDescripcion() Sets the current record's "descripcion" value
 * @method FotografiaAnuncio setFotografia()  Sets the current record's "fotografia" value
 * @method FotografiaAnuncio setBorrado()     Sets the current record's "borrado" value
 * @method FotografiaAnuncio setActivo()      Sets the current record's "activo" value
 * @method FotografiaAnuncio setAnuncio()     Sets the current record's "Anuncio" value
 * 
 * @package    anuncios
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFotografiaAnuncio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fotografiaAnuncio');
        $this->hasColumn('idAnuncio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fotografia', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '1',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anuncio', array(
             'local' => 'idAnuncio',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}