<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comentario', 'doctrine');

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idAnuncio
 * @property string $nombre
 * @property string $correo
 * @property string $telefono
 * @property text $texto
 * @property boolean $borrado
 * @property boolean $activo
 * @property Anuncio $Anuncio
 * 
 * @method integer    getIdAnuncio() Returns the current record's "idAnuncio" value
 * @method string     getNombre()    Returns the current record's "nombre" value
 * @method string     getCorreo()    Returns the current record's "correo" value
 * @method string     getTelefono()  Returns the current record's "telefono" value
 * @method text       getTexto()     Returns the current record's "texto" value
 * @method boolean    getBorrado()   Returns the current record's "borrado" value
 * @method boolean    getActivo()    Returns the current record's "activo" value
 * @method Anuncio    getAnuncio()   Returns the current record's "Anuncio" value
 * @method Comentario setIdAnuncio() Sets the current record's "idAnuncio" value
 * @method Comentario setNombre()    Sets the current record's "nombre" value
 * @method Comentario setCorreo()    Sets the current record's "correo" value
 * @method Comentario setTelefono()  Sets the current record's "telefono" value
 * @method Comentario setTexto()     Sets the current record's "texto" value
 * @method Comentario setBorrado()   Sets the current record's "borrado" value
 * @method Comentario setActivo()    Sets the current record's "activo" value
 * @method Comentario setAnuncio()   Sets the current record's "Anuncio" value
 * 
 * @package    anuncios
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('idAnuncio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('correo', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('telefono', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('texto', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '1',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anuncio', array(
             'local' => 'idAnuncio',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}