<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Anuncio', 'doctrine');

/**
 * BaseAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property text $descripcion
 * @property string $precio
 * @property enum $efectividadAnuncio
 * @property integer $idCategoriaAnuncio
 * @property integer $idProvinciaAnuncio
 * @property string $codigoPostal
 * @property enum $tipoAnuncio
 * @property text $enlaceVideo
 * @property boolean $borrado
 * @property boolean $activo
 * @property Doctrine_Collection $FotografiaAnuncio
 * @property CategoriaAnuncio $CategoriaAnuncio
 * @property ProvinciaAnuncio $ProvinciaAnuncio
 * @property UsuarioAnuncio $UsuarioAnuncio
 * @property Doctrine_Collection $Comentario
 * 
 * @method string              getTitulo()             Returns the current record's "titulo" value
 * @method text                getDescripcion()        Returns the current record's "descripcion" value
 * @method string              getPrecio()             Returns the current record's "precio" value
 * @method enum                getEfectividadAnuncio() Returns the current record's "efectividadAnuncio" value
 * @method integer             getIdCategoriaAnuncio() Returns the current record's "idCategoriaAnuncio" value
 * @method integer             getIdProvinciaAnuncio() Returns the current record's "idProvinciaAnuncio" value
 * @method string              getCodigoPostal()       Returns the current record's "codigoPostal" value
 * @method enum                getTipoAnuncio()        Returns the current record's "tipoAnuncio" value
 * @method text                getEnlaceVideo()        Returns the current record's "enlaceVideo" value
 * @method boolean             getBorrado()            Returns the current record's "borrado" value
 * @method boolean             getActivo()             Returns the current record's "activo" value
 * @method Doctrine_Collection getFotografiaAnuncio()  Returns the current record's "FotografiaAnuncio" collection
 * @method CategoriaAnuncio    getCategoriaAnuncio()   Returns the current record's "CategoriaAnuncio" value
 * @method ProvinciaAnuncio    getProvinciaAnuncio()   Returns the current record's "ProvinciaAnuncio" value
 * @method UsuarioAnuncio      getUsuarioAnuncio()     Returns the current record's "UsuarioAnuncio" value
 * @method Doctrine_Collection getComentario()         Returns the current record's "Comentario" collection
 * @method Anuncio             setTitulo()             Sets the current record's "titulo" value
 * @method Anuncio             setDescripcion()        Sets the current record's "descripcion" value
 * @method Anuncio             setPrecio()             Sets the current record's "precio" value
 * @method Anuncio             setEfectividadAnuncio() Sets the current record's "efectividadAnuncio" value
 * @method Anuncio             setIdCategoriaAnuncio() Sets the current record's "idCategoriaAnuncio" value
 * @method Anuncio             setIdProvinciaAnuncio() Sets the current record's "idProvinciaAnuncio" value
 * @method Anuncio             setCodigoPostal()       Sets the current record's "codigoPostal" value
 * @method Anuncio             setTipoAnuncio()        Sets the current record's "tipoAnuncio" value
 * @method Anuncio             setEnlaceVideo()        Sets the current record's "enlaceVideo" value
 * @method Anuncio             setBorrado()            Sets the current record's "borrado" value
 * @method Anuncio             setActivo()             Sets the current record's "activo" value
 * @method Anuncio             setFotografiaAnuncio()  Sets the current record's "FotografiaAnuncio" collection
 * @method Anuncio             setCategoriaAnuncio()   Sets the current record's "CategoriaAnuncio" value
 * @method Anuncio             setProvinciaAnuncio()   Sets the current record's "ProvinciaAnuncio" value
 * @method Anuncio             setUsuarioAnuncio()     Sets the current record's "UsuarioAnuncio" value
 * @method Anuncio             setComentario()         Sets the current record's "Comentario" collection
 * 
 * @package    epi
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnuncio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anuncio');
        $this->hasColumn('titulo', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('precio', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('efectividadAnuncio', 'enum', 8, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'normal',
              1 => 'semi-destacado(2€)',
              2 => 'destacado(5€)',
              3 => 'premium(8€)',
              4 => 'gold(10€)',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('idCategoriaAnuncio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('idProvinciaAnuncio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('codigoPostal', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('tipoAnuncio', 'enum', 8, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'compra',
              1 => 'vende',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('enlaceVideo', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '1',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FotografiaAnuncio', array(
             'local' => 'id',
             'foreign' => 'idAnuncio'));

        $this->hasOne('CategoriaAnuncio', array(
             'local' => 'idCategoriaAnuncio',
             'foreign' => 'id'));

        $this->hasOne('ProvinciaAnuncio', array(
             'local' => 'idProvinciaAnuncio',
             'foreign' => 'id'));

        $this->hasOne('UsuarioAnuncio', array(
             'local' => 'id',
             'foreign' => 'idAnuncio'));

        $this->hasMany('Comentario', array(
             'local' => 'id',
             'foreign' => 'idAnuncio'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}