<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ContactoAnuncio', 'doctrine');

/**
 * BaseContactoAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idAnuncio
 * @property string $nombre
 * @property string $email
 * @property string $telefono
 * @property text $mensaje
 * @property boolean $borrado
 * @property Anuncio $Anuncio
 * 
 * @method integer         getIdAnuncio() Returns the current record's "idAnuncio" value
 * @method string          getNombre()    Returns the current record's "nombre" value
 * @method string          getEmail()     Returns the current record's "email" value
 * @method string          getTelefono()  Returns the current record's "telefono" value
 * @method text            getMensaje()   Returns the current record's "mensaje" value
 * @method boolean         getBorrado()   Returns the current record's "borrado" value
 * @method Anuncio         getAnuncio()   Returns the current record's "Anuncio" value
 * @method ContactoAnuncio setIdAnuncio() Sets the current record's "idAnuncio" value
 * @method ContactoAnuncio setNombre()    Sets the current record's "nombre" value
 * @method ContactoAnuncio setEmail()     Sets the current record's "email" value
 * @method ContactoAnuncio setTelefono()  Sets the current record's "telefono" value
 * @method ContactoAnuncio setMensaje()   Sets the current record's "mensaje" value
 * @method ContactoAnuncio setBorrado()   Sets the current record's "borrado" value
 * @method ContactoAnuncio setAnuncio()   Sets the current record's "Anuncio" value
 * 
 * @package    anuncios
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactoAnuncio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactoAnuncio');
        $this->hasColumn('idAnuncio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('mensaje', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anuncio', array(
             'local' => 'idAnuncio',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}