<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioAnuncio', 'doctrine');

/**
 * BaseUsuarioAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idAnuncio
 * @property string $nombre
 * @property string $correo
 * @property string $telefono
 * @property enum $tipo
 * @property Doctrine_Collection $Anuncio
 * 
 * @method integer             getIdAnuncio() Returns the current record's "idAnuncio" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method string              getCorreo()    Returns the current record's "correo" value
 * @method string              getTelefono()  Returns the current record's "telefono" value
 * @method enum                getTipo()      Returns the current record's "tipo" value
 * @method Doctrine_Collection getAnuncio()   Returns the current record's "Anuncio" collection
 * @method UsuarioAnuncio      setIdAnuncio() Sets the current record's "idAnuncio" value
 * @method UsuarioAnuncio      setNombre()    Sets the current record's "nombre" value
 * @method UsuarioAnuncio      setCorreo()    Sets the current record's "correo" value
 * @method UsuarioAnuncio      setTelefono()  Sets the current record's "telefono" value
 * @method UsuarioAnuncio      setTipo()      Sets the current record's "tipo" value
 * @method UsuarioAnuncio      setAnuncio()   Sets the current record's "Anuncio" collection
 * 
 * @package    anuncios
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioAnuncio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuarioAnuncio');
        $this->hasColumn('idAnuncio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('correo', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('telefono', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('tipo', 'enum', 8, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'particular',
              1 => 'profesional',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Anuncio', array(
             'local' => 'idAnuncio',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}