<?php

/**
 * CategoriaAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaAnuncio');
    }
}