<?php

/**
 * UsuarioAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioAnuncio');
    }
}