# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    #texto tinymc
    rich_text_js_dir:  js/tiny_mce     
    # Form security secret (CSRF protection)
    csrf_secret:            30905ebdd8f8f12fb317b60c3e22568a16051832
    enabled_modules:        [default, sfGuardAuth, sfMediaBrowser, sfGuardForgotPassword, sfCaptchaGD]
    standard_helpers:       [Partial, Cache, I18N]
    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
  
    i18n:  true
    default_culture:  es   
    
  .actions:
    
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure 

    
    
