<?php

/**
 * ContactoAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactoAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactoAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactoAnuncio');
    }
}