<?php

/**
 * FotografiaAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotografiaAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotografiaAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotografiaAnuncio');
    }
}