<?php

/**
 * ProvinciaAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProvinciaAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProvinciaAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProvinciaAnuncio');
    }
}