Anuncio:
  connection: doctrine
  tableName: anuncio
  actAs:
    Timestampable:
  columns:
    titulo:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    precio:
      type: double(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false         
#    efectividadAnuncio:
#      type: enum(30)
#      fixed: false
#      unsigned: false
#      values:
#        - normal
#        - semi-destacado(2€)
#        - destacado(5€)
#        - premium(8€)
#        - gold(10€)
#      primary: false
#      notnull: true
#      autoincrement: false
    fechaInicio:
      type: date()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fechaFin:
      type: date()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false      
    idCategoriaAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    idProvinciaAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false 
    localidad:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false       
    codigoPostal:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false      
    tipoAnuncio:
      type: enum(30)
      fixed: false
      unsigned: false
      values:  
        - vende
        - compra
      primary: false
      notnull: true
      autoincrement: false
    enlaceVideo:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false      
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false       
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    nombre:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    correo:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telefono:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false         
    tipo:
      type: enum(30)
      fixed: false
      unsigned: false
      values:
        - particular
        - profesional
      primary: false
      notnull: true
      autoincrement: false   
    visitas:
      type: integer(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: 0
      autoincrement: false   
    votoPositivo:
      type: integer(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: 0
      autoincrement: false   
    votoNegativo:
      type: integer(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: 0
      autoincrement: false         
  relations:
    FotografiaAnuncio:
      local: id
      foreign: idAnuncio
      type: many 
    CategoriaAnuncio:
      local: idCategoriaAnuncio
      foreign: id
      type: one    
    ProvinciaAnuncio:
      local: idProvinciaAnuncio
      foreign: id
      type: one    
    Comentario:
      local: id
      foreign: idAnuncio
      type: many      
    DenunciaAnuncio:
      local: id
      foreign: idAnuncio
      type: many       
    ContactoAnuncio:
      local: id
      foreign: idAnuncio
      type: many          
      
FotografiaAnuncio:
  connection: doctrine
  tableName: fotografiaAnuncio
  actAs:
    Timestampable:
  columns:
    idAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false        
    descripcion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fotografia:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false        
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false       
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false 
  relations:
    Anuncio:
      local: idAnuncio
      foreign: id
      type: one
      
      
CategoriaAnuncio:
  connection: doctrine
  tableName: categoriaAnuncio
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Anuncio:
      local: id
      foreign: idCategoriaAnuncio
      type: many     
      
ProvinciaAnuncio:
  connection: doctrine
  tableName: provinciaAnuncio
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Anuncio:
      local: id
      foreign: idProvinciaAnuncio
      type: many        
    
Comentario:
  connection: doctrine
  tableName: comentario
  actAs:
    Timestampable:
  columns:
    idAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    nombre:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    correo:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telefono:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false        
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false       
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false 
  relations:
    Anuncio:
      local: idAnuncio
      foreign: id
      type: one          
 
Contenido:
  connection: doctrine
  tableName: contenido
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idCategoriaContenido:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    titulo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    contenido:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false 
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one
    CategoriaContenido:
      local: idCategoriaContenido
      foreign: id
      type: one  
      
CategoriaContenido:
  connection: doctrine
  tableName: categoriaContenido
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    Contenido:
      local: id
      foreign: idCategoriaContenido
      type: many


Contacto:
  connection: doctrine
  tableName: contacto
  actAs:
    Timestampable:  
  columns:
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telefono:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    empresa:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    comentario:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    documento:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false  

Configuracion:
  connection: doctrine
  tableName: configuracion
  actAs:
    Timestampable:  
  columns:
    variable:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    valor:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion:
      type: blob()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tipo:
      type: enum(30)
      fixed: false
      unsigned: false
      values:
        - imagen
        - variable
        - mensaje
      primary: false
      notnull: true
      autoincrement: false      
      
DenunciaAnuncio:
  connection: doctrine
  tableName: denunciaAnuncio
  actAs:
    Timestampable:  
  columns:
    idAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telefono:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    empresa:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    razonAnuncio:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    documento:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    solucionado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
  relations:
    Anuncio:
      local: idAnuncio
      foreign: id
      type: one     
      
ContactoAnuncio:
  connection: doctrine
  tableName: contactoAnuncio
  actAs:
    Timestampable:  
  columns:
    idAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telefono:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    mensaje:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false      
  relations:
    Anuncio:
      local: idAnuncio
      foreign: id
      type: one           
      