# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [administracion.css,jquery-ui-1.8.17.custom.css, /resources/css/jquery.toastmessage.css, ie.css, /sfMediaBrowserPlugin/css/list.css]

  javascripts:    [jquery-1.7.2.min.js, jquery-ui-1.8.17.custom.min.js, tiny_mce/tiny_mce, administracion.js, jquery.toastmessage.js]

  has_layout:     true
  layout:         layout
