Anuncio:
  connection: doctrine
  tableName: anuncio
  actAs:
    Timestampable:
  columns:
    titulo:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    precio:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false   
    efectividadAnuncio:
      type: enum(8)
      fixed: false
      unsigned: false
      values:
        - normal
        - semi-destacado(2€)
        - destacado(5€)
        - premium(8€)
        - gold(10€)
      primary: false
      notnull: true
      autoincrement: false
    idCategoriaAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    idProvinciaAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false 
    codigoPostal:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false      
    tipoAnuncio:
      type: enum(8)
      fixed: false
      unsigned: false
      values:
        - compra
        - vende
      primary: false
      notnull: true
      autoincrement: false
    enlaceVideo:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false      
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false       
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "1"
      autoincrement: false 
  relations:
    FotografiaAnuncio:
      local: id
      foreign: idAnuncio
      type: many 
    CategoriaAnuncio:
      local: idCategoriaAnuncio
      foreign: id
      type: one    
    ProvinciaAnuncio:
      local: idProvinciaAnuncio
      foreign: id
      type: one    
    UsuarioAnuncio:
      local: id
      foreign: idAnuncio
      type: one           
      
FotografiaAnuncio:
  connection: doctrine
  tableName: fotografiaAnuncio
  actAs:
    Timestampable:
  columns:
    idAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false        
    descripcion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fotografia:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false        
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false       
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "1"
      autoincrement: false 
  relations:
    Anuncio:
      local: idAnuncio
      foreign: id
      type: one
      
      
CategoriaAnuncio:
  connection: doctrine
  tableName: categoriaAnuncio
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Anuncio:
      local: id
      foreign: idCategoriaAnuncio
      type: many     
      
ProvinciaAnuncio:
  connection: doctrine
  tableName: provinciaAnuncio
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Anuncio:
      local: id
      foreign: idProvinciaAnuncio
      type: many        
      
      
UsuarioAnuncio:
  connection: doctrine
  tableName: usuarioAnuncio
  actAs:
    Timestampable:
  columns:
    idAnuncio:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false        
    nombre:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    correo:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telefono:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false         
    tipo:
      type: enum(8)
      fixed: false
      unsigned: false
      values:
        - particular
        - profesional
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Anuncio:
      local: idAnuncio
      foreign: id
      type: many        